export interface CharacterMapping {
    base: string;
    alt: string;
    block: string;
}

export const Letters = {
    uppercase: [
        { base: "A", alt: "А", block: "Cyrillic" },
        { base: "B", alt: "В", block: "Cyrillic" },
        { base: "C", alt: "С", block: "Cyrillic" },
        { base: "D", alt: "D", block: "Cyrillic" },
        { base: "E", alt: "Е", block: "Cyrillic" },
        { base: "F", alt: "", block: "" },
        { base: "G", alt: "", block: "" },
        { base: "H", alt: "Н", block: "Cyrillic" },
        { base: "I", alt: "І", block: "Cyrillic" },
        { base: "J", alt: "Ј", block: "Cyrillic" },
        { base: "K", alt: "К", block: "Cyrillic" },
        { base: "L", alt: "", block: "" },
        { base: "M", alt: "М", block: "Cyrillic" },
        { base: "N", alt: "Ν", block: "Greek and Coptic" },
        { base: "O", alt: "О", block: "Cyrillic" },
        { base: "P", alt: "Р", block: "Cyrillic" },
        { base: "Q", alt: "", block: "" },
        { base: "R", alt: "", block: "" },
        { base: "S", alt: "Ѕ", block: "Cyrillic" },
        { base: "T", alt: "Т", block: "Cyrillic" },
        { base: "U", alt: "", block: "" },
        { base: "V", alt: "", block: "" },
        { base: "W", alt: "", block: "" },
        { base: "X", alt: "Х", block: "Cyrillic" },
        { base: "Y", alt: "Ү", block: "Cyrillic" },
        { base: "Z", alt: "Ζ", block: "Greek and Coptic" },
    ] as CharacterMapping[],

    lowercase: [
        { base: "a", alt: "а", block: "Cyrillic" },
        { base: "b", alt: "", block: "" },
        { base: "c", alt: "с", block: "Cyrillic" },
        { base: "d", alt: "", block: "" },
        { base: "e", alt: "е", block: "Cyrillic" },
        { base: "f", alt: "", block: "" },
        { base: "g", alt: "", block: "" },
        { base: "h", alt: "һ", block: "Cyrillic" },
        { base: "i", alt: "і", block: "Cyrillic" },
        { base: "j", alt: "ј", block: "Cyrillic" },
        { base: "k", alt: "", block: "" },
        { base: "l", alt: "l", block: "Cyrillic" },
        { base: "m", alt: "", block: "" },
        { base: "n", alt: "", block: "" },
        { base: "o", alt: "о", block: "Cyrillic" },
        { base: "p", alt: "р", block: "Cyrillic" },
        { base: "q", alt: "", block: "" },
        { base: "r", alt: "", block: "" },
        { base: "s", alt: "ѕ", block: "Cyrillic" },
        { base: "t", alt: "", block: "" },
        { base: "u", alt: "", block: "" },
        { base: "v", alt: "", block: "" },
        { base: "w", alt: "", block: "" },
        { base: "x", alt: "х", block: "Cyrillic" },
        { base: "y", alt: "у", block: "Cyrillic" },
        { base: "z", alt: "", block: "" },
    ] as CharacterMapping[],

    numbers: [
        { base: "0", alt: "", block: "" },
        { base: "1", alt: "", block: "" },
        { base: "2", alt: "", block: "" },
        { base: "3", alt: "З", block: "Cyrillic" },
        { base: "4", alt: "", block: "" },
        { base: "5", alt: "", block: "" },
        { base: "6", alt: "", block: "" },
        { base: "7", alt: "", block: "" },
        { base: "8", alt: "", block: "" },
        { base: "9", alt: "", block: "" },
    ] as CharacterMapping[],

    symbols: [
        { base: "/", alt: "∕", block: "Mathematical Operators" },
        { base: "!", alt: "ǃ", block: "Latin Extended-B" },
        { base: ".", alt: "․", block: "General Punctuation" },
        { base: ",", alt: "‚", block: "General Punctuation" },
        { base: ";", alt: ";", block: "General Punctuation" },
        { base: '"', alt: "", block: "" },
        { base: "@", alt: "", block: "" },
        { base: "#", alt: "", block: "" },
        { base: "$", alt: "", block: "" },
        { base: "%", alt: "", block: "" },
        { base: "^", alt: "", block: "" },
        { base: "&", alt: "", block: "" },
        { base: "*", alt: "", block: "" },
        { base: "(", alt: "", block: "" },
        { base: ")", alt: "", block: "" },
        { base: "`", alt: "", block: "" },
        { base: "-", alt: "", block: "" },
        { base: "=", alt: "", block: "" },
        { base: "[", alt: "", block: "" },
        { base: "]", alt: "", block: "" },
        { base: "\\", alt: "", block: "" },
        { base: "'", alt: "", block: "" },
        { base: "~", alt: "", block: "" },
        { base: "_", alt: "", block: "" },
        { base: "+", alt: "", block: "" },
        { base: "{", alt: "", block: "" },
        { base: "}", alt: "", block: "" },
        { base: "|", alt: "", block: "" },
        { base: ":", alt: "", block: "" },
        { base: "<", alt: "", block: "" },
        { base: ">", alt: "", block: "" },
        { base: "?", alt: "", block: "" },
    ] as CharacterMapping[],

    spaces: [{ base: " ", alt: " ", block: "General Punctuation" }] as CharacterMapping[],
};

export const LettersDisplay = {
    uppercase: {
        display: "Spoof Uppercase Letters",
        description: "",
    },
    lowercase: {
        display: "Spoof Lowercase Letters",
        description: "",
    },
    numbers: {
        display: "Spoof Numbers",
        description: "",
    },
    symbols: {
        display: "Spoof Symbols",
        description: "",
    },
    spaces: {
        display: "Spoof Spaces",
        description: "Replace regular spaces with 1/4em spaces.",
    },
};
